theme:
  default: normal
  type: enum
  choices:
    - green 
    - zeit 
    - informator
    - sportverlag
    - beyer
    - falken
    - blue

piece_style:
  default: merida
  type: enum
  choices:
    - merida
    - case
    - wikipedia
    - alpha
    - uscf
    - condal
    - maya
    - leipzig

locale:
  default: en
  type: enum
  choices:
    - cs
    - da
    - de
    - en
    - es
    - et
    - fi
    - fr
    - hu
    - is
    - it
    - nb
    - nl
    - pl
    - pt
    - ro
    - sv

marker:
  default: true
  type: bool
  
inner_coords:
  default: false
  type: bool
