theme:
  default: normal
  type: enum
  choices:
    - green 
    - zeit 
    - informator
    - sportverlag
    - beyer
    - falken
    - blue

piece_style:
  default: merida
  type: enum
  choices:
    - merida
    - case
    - wikipedia
    - alpha
    - uscf
    - condal
    - maya
    - leipzig

